# Generated by Django 4.2.7 on 2023-12-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_marca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='nombre',
            new_name='name',
        ),
    ]
