# Generated by Django 4.2.7 on 2023-12-21 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_marca_options_rename_nombre_marca_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
