# Generated by Django 4.2.7 on 2024-01-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_marca_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
