# Generated by Django 4.2.7 on 2023-11-27 20:31

import apps.blog.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('thumbnail', models.ImageField(max_length=500, upload_to=apps.blog.models.blog_thumbnail_directory)),
                ('media_file', models.FileField(blank=True, upload_to=apps.blog.models.blog_thumbnail_directory)),
                ('description', models.TextField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('service_type', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('reparacion', 'Reparacion'), ('personalizacion', 'Personalizacion')], max_length=50)),
                ('bike_model', models.CharField(max_length=50)),
                ('service_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('completion_date', models.DateField()),
                ('time_read', models.IntegerField()),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogpost_view_count', to='blog.post')),
            ],
        ),
    ]
